### ISSUE TITLE
Invite?

### ISSUE THREAD

**Issue by ghost** [ncsuarc/interop_clients#8]
Hey! My name is Josh Starmer, I am a freshman -- I just joined the club, could you guys send me an invite so I can join your organization?

**Comment by elihunter173** [comment]
Done and thanks!

Just for the future (no worries this time), please only put issues that a project-specific in the project's issue tracker. It just makes it easier to find and prioritize tasks if they are all relevant. Organizational things like this can go on our redmine (I'll show you) or just in slack/email to aerialrobotics@ncsu.edu

**Comment by ghost** [comment]
Ok thanks! Will Do!
